In [13]:
#NUMPY
#Numpy is he backbone of Machine Learning in Python.
#It is one of the most important libraries in Python for numerical computations.
#It adds support to core Python for multi-dimensional arrays (and matrices) and fast vectorized operations on these arrays.



#importing numpy module
import numpy as np


#declaring array
A=np.array([1, 3, 5, 7, 9, 11])
print(A)
print("\n")
# Creating a list named "a"
a = [1, 2, 3, 4, 5]
# Creating a numpy array from the list
np.array([range(i, i + 4) for i in a])


# Create an array of ones
print(np.ones((3,4)))
print("\n")

# Create an array of zeros
print(np.zeros((2,3,4),dtype=np.int16))
print("\n")

# Create an array with random values
print(np.random.random((2,2)))
print("\n")

# Create an empty array
print(np.empty((3,2)))
print("\n")

# Create a full array
print(np.full((2,2),7))
print("\n")

# Create an array of evenly-spaced values
print(np.arange(10,25,5))
print("\n")

# Create an array of evenly-spaced values
print(np.linspace(0,2,9))
print("\n")


#Arranging array 
arr = np.arange(9).reshape(3,3)
print(arr)

[ 1  3  5  7  9 11]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


[[0.68658162 0.28165139]
 [0.74090239 0.61535814]]


[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[7 7]
 [7 7]]


[10 15 20]


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#Lets come to matrix operations using numpy module

import numpy as np

#declaring two matrices of 3x3 Dimension
x=np.array([[3,4,6], [7,2,0], [9,11,10]])
y=np.array([[1,2,3], [4,5,6], [7,8,9]])


#Adding matrices
print("\nAddition of two Matrices : ")
print(np.add(x,y))


#Subtracting Matrices
print("\nSubtraction of two Matrices : ")
print(np.subtract(x,y))


#Multiplying Matrices
print("\nMultiplication of two Matrices : ")
print(np.multiply(x,y))


#Dividing Matrices
print("\nDivision of two Matrices : ")
print(np.divide(x,y))


#Transpose of Matrix x
print("\nTranspose Matrix of x : ")
print(x.T)


#Transpose of Matrix y
print("\nTranspose Matrix of y : ")
print(y.T)


Addition of two Matrices : 
[[ 4  6  9]
 [11  7  6]
 [16 19 19]]

Subtraction of two Matrices : 
[[ 2  2  3]
 [ 3 -3 -6]
 [ 2  3  1]]

Multiplication of two Matrices : 
[[ 3  8 18]
 [28 10  0]
 [63 88 90]]

Division of two Matrices : 
[[3.         2.         2.        ]
 [1.75       0.4        0.        ]
 [1.28571429 1.375      1.11111111]]

Transpose Matrix of x : 
[[ 3  7  9]
 [ 4  2 11]
 [ 6  0 10]]

Transpose Matrix of y : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
